name: myenv
channels:
  - conda-forge
depndencies:
  - python
  - black
  - bokeh
  - dask
  - distributed
  - h5py
  - matplotlib
  - numba
  - numpy
  - pandas
  - pylint
  - scikit-image
  - scipy
  - tqdm