name: myenv
channels:
  - conda-forge
dependencies:
  - black
  - bokeh
  - dask
  - distributed
  - h5py
  - matplotlib
  - numba
  - numpy
  - pandas
  - pylint
  - python=3.9
  - scikit-image
  - scipy
  - sympy
  - tqdm